name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: powershell

jobs:
  # Build Docker Image
  build:
    name: Build Docker Image
    runs-on: windows-2022
    steps:

    # Login to Docker
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    # run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # Ensure Access to Unreal Engine Repository
    - name: Ensure Access to Unreal Engine Repository
      run: git ls-remote --heads https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/EpicGames/UnrealEngine.git

    # Install ue4-docker
    - name: Install ue4-docker
      run: pip install git+https://github.com/adamrehn/ue4-docker@00fe69849d6c1e098bc276f9797e9b7542e7d55b

    # Close Docker
    - name: Close Docker
      run: Stop-Service *docker*

    # Edit Docker Daemon Configuration
    - name: Edit Docker Daemon Configuration
      run: | 
        Set-Content -Path C:\ProgramData\Docker\config\daemon.json -Value '{
          "registry-mirrors": [],
          "insecure-registries": [],
          "debug": false,
          "experimental": false,
          "storage-opts": [
            "size=400GB"
          ]
        }'

    # Restart Docker
    - name: Restart Docker
      run: Start-Service *docker*

    # Setup Build Environment
    - name: Setup Build Environment
      run: ue4-docker setup

    # Build Unreal Engine Image
    - name: Build Unreal Engine Image
      run: ue4-docker build 4.27.0 -basetag ltsc2022 --visual-studio 2019 --no-full --no-engine -username ${{ secrets.GH_USERNAME }} -password ${{ secrets.GH_TOKEN }}
      
    # Push Unreal Engine Image to Docker Repository
    - name: Push Unreal Engine Image to Docker Repository
      run: |
        docker image tag adamrehn/ue4-minimal:4.27.0-ltsc2022-vs2019 ${{ secrets.DOCKER_REPOSITORY }}:unreal-engine-4.27.0 ;
        docker image push ${{ secrets.DOCKER_REPOSITORY }}:unreal-engine-4.27.0
        
