name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Build Docker Image
  build:
    name: Build Docker Image
    runs-on: windows-2022
    steps:

    # Log Disk Space
    - name: Log Disk Space
      shell: bash
      run: df -h

    # Install ue4-docker
    - name: Install ue4-docker
      run: pip install ue4-docker
      
    # Docker - Temporarily Close Docker
    - name: Docker - Temporarily Close Docker
      shell: powershell
      run: Stop-Service *docker*

    # Docker - Edit Daemon Configuration
    - name: Docker - Configure Max Container Size
      shell: powershell
      run: | 
          Set-Content -Path C:\ProgramData\Docker\config\daemon.json -Value '{
            "registry-mirrors": [],
            "insecure-registries": [],
            "debug": false,
            "experimental": false,
            "storage-opts": [
              "size=400GB"
            ]
          }' >> test.txt

    # Docker - Switch to Windows Daemon
    - name: Docker - Switch to Windows Daemon
      shell: powershell
      run: '& "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchWindowsEngine'
