name: Build

# Required Secrets
# DOCKER_USERNAME
# DOCKER_TOKEN
# IMAGE_TAG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
defaults:
  run:
    shell: powershell

jobs:
  # Build
  build:
    name: Build for ${{ matrix.PLATFORM }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
       PLATFORM:
       - Win64
       - Linux
       - Mac
    steps:

    # Checkout Super-Florida-Man
    - name: Checkout Super-Florida-Man
      uses: actions/checkout@v2.3.5
      with:
          lfs: false
    
    # Build Game
    - name: Build Game
      uses: addnab/docker-run-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image: ${{ secrets.IMAGE_TAG }}
        options: -v ${{ github.workspace }}:/Project
        run: |
          cd Project ;
          ue4 package Shipping -platform=${{ matrix.PLATFORM }}
    
    # Upload Game
    - name: Upload Game
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Build-Win64
        path: dist
